baseURL : 'https://mohammod.github.io/'
languageCode : 'en-us'
title : 'Mohammod Naimul Islam Suvon'

theme : "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1
#    - identifier: gallery
#      name: Gallery
#      title: Blog posts
#      url: /gallery
#      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Mohammod"
  description:
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/page_icon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Mohammod" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableAchievements: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableContact: false
      disableProexperience: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Mohammod."
    subtitle: " I'm an AI researcher"
    content: "I leverage my expertise in machine learning, multimodal learning natural language processing, and other related fields to create innovative AI solutions that can transform industries and enhance people's lives."
    image: "/images/profile.png"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Mdnaimulislam
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/md-naimul/
      customIcons:
        - icon: /images/google_scholar_icon.png
          url: "https://scholar.google.com/citations?user=DGYUifQAAAAJ&hl=en"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/profile.png"
    content: |-
      I am a Research Assistant in Machine Learning for Medical Image Analysis at the Department of Computer Science at the University of Sheffield. I have a background in computer science, specifically in speech and language processing, and I have a strong interest in the interaction between multiple modalities of data.
      
      I am currently working on a project that will help in the diagnosis and critical care of patients with Pulmonary Arterial Hypertension (PAH).
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "PyTorch"
        - "Scikit-learn"
        - "GIT"
        - "Jupyter Notebook"
        - "HPC"

  # Achievements
  achievements:
    enable: true
    title: "Honors and Awards"
    items:
      - title: Fretwell-Downing Prize
        content: I received the Best Dissertation Award for my MSc degree at the University of Sheffield during the academic session of 2021/2022.

      - title: Academic Excellency Scholarship (25% Tuition fee waiver)
        content: I received 25% scholarship from North South university during my BSc.

      - title: Academic Year 2021/22 Performance with Distinction Award at the University of Sheffield

      - title: Academic Year 2017/20 Performance with Cum Laude (Distinction) at North South University



  # Experience
  experience:
    enable: false
    title: "Professional & Teaching Experience"
    items:
      - job: "Reseach Assistant in Machine Learning for Medical Image Analysis"
        company: "The University of Sheffield"
        companyUrl: "https://www.sheffield.ac.uk/"
        date: "April 2023 - present"

      - job: "Data analysis & Website Maintenance - Turing Network Development Award (TNDA)"
        company: "The University of Sheffield"
        companyUrl: "https://www.sheffield.ac.uk/"
        date: "February 2023 - March 2023"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://shef-ai.github.io/"
        content: |
          I have assisted in updating the information on the Sheffield AI website, as well as building the AIRE and MultimodalAI workshop websites using Hugo.

      - job: "Course Support - An Introduction to Transparent Machine Learning"
        company: "Alan Turing Institute"
        companyUrl: "https://www.turing.ac.uk/"
        date: "November 2022 - January 2023"
        featuredLink:
          enable: true
          url: "https://pykale.github.io/transparentML/"
        info:
          enable: true
        content: |
          I have assisted in the development of a course on "An Introduction to Transparent Machine Learning," which is part of the Alan Turing Institute's online learning courses in responsible AI. In this role, I have contributed to all of the course's exercises and quizzes.

      - job: "Research Support - Turing Network Development Award (TNDA)"
        company: "The University of Sheffield"
        companyUrl: "https://www.sheffield.ac.uk/"
        date: "Sep 2022 - Oct 2022"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://shef-ai.github.io/"
        content: |
          I have assisted in updating the information on the Sheffield AI website.

      - job: "Cover Teacher"
        company: "Education World, Sheffield"
        companyUrl: "https://education-world.co.uk/our-team/south-yorkshire-team/"
        date: "December 2021 - August 2022"
        content: |
          I have worked as a supply teacher for various secondary schools near Sheffield.

      - job: "Senior Software Engineer"
        company: "Robo Tech Valley"
        companyUrl: "https://www.robotechvalley.com/"
        date: "January 2021 - August 2021"
        content: |
          I have created an Android app that controls a small educational robot named EduBot.

      - job: "Teaching Assistant"
        company: "North South University"
        companyUrl: "http://www.northsouth.edu/"
        date: "January 2020 - August 2021"

      - job: "Full Stack Web Developer (Internship)"
        company: "BUET E-learning Research and Development Lab"
        companyUrl: "https://esrdlab.cse.buet.ac.bd/"
        date: "September 2020 - December 2020"

  # Professional & Teaching Experience
  proexperience:
    enable: true
    title: "Professional & Teaching Experience"
    index: false
    items:
      - title: "Reseach Assistant in Machine Learning for Medical Image Analysis"
        school:
          name: "The University of Sheffield"
          url: "https://www.sheffield.ac.uk/"
        date: "April 2023 - present"
        content: "sdaadad"

      - title: "Data analysis & Website Maintenance - Turing Network Development Award (TNDA)"
        school:
          name: "The University of Sheffield"
          url: "https://www.sheffield.ac.uk/"
        date: "February 2023 - March 2023"
        content: "I have assisted in updating the information on the Sheffield AI website, as well as building the AIRE and MultimodalAI workshop websites using Hugo."

      - title: "Course Support - An Introduction to Transparent Machine Learning"
        school:
          name: "Alan Turing Institute"
          url: "https://www.turing.ac.uk/"
        date: "November 2022 - January 2023"
        content: I have assisted in the development of a course on "An Introduction to Transparent Machine Learning," which is part of the Alan Turing Institute's online learning courses in responsible AI. In this role, I have contributed to all of the course's exercises and quizzes.

      - title: "Research Support - Turing Network Development Award (TNDA)"
        school:
          name: "The University of Sheffield"
          url: "https://www.sheffield.ac.uk/"
        date: "Sep 2022 - Oct 2022"
        content: "I have assisted in updating the information on the Sheffield AI website."

      - title: "Cover Teacher"
        school:
          name: "Education World, Sheffield"
          url: "https://education-world.co.uk/our-team/south-yorkshire-team/"
        date: "December 2021 - August 2022"
        content: "I have worked as a supply teacher for various secondary schools near Sheffield."

      - title: "Senior Software Engineer"
        school:
          name: "Robo Tech Valley"
          url: "https://www.robotechvalley.com/"
        date: "January 2021 - August 2021"
        content: "I have created an Android app that controls a small educational robot named EduBot."

      - title: "Teaching Assistant"
        school:
          name: "North South University"
          url: "http://www.northsouth.edu/"
        date: "January 2020 - August 2021"

      - title: "Full Stack Web Developer (Internship)"
        school:
          name: "BUET E-learning Research and Development Lab"
          url: "https://esrdlab.cse.buet.ac.bd/"
        date: "September 2020 - December 2020"



  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "MSc (Completion with Distinction) in Computer Science with Speech and Language Processing."
        school:
          name: "The University of Sheffield"
          url: "https://www.sheffield.ac.uk/"
        date: "2021 - 2022"
        Percentage: "83 out of 100"

      - title: "BSc (Completion with Distinction) in Computer Science and Engineering. "
        school:
          name: "North South University"
          url: "http://www.northsouth.edu/"
        date: "2017 - 2020"
        CGPA: "3.53 out of 4.0"


  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: PyKale
        content: A library built upon PyTorch for multimodal learning and transfer learning from multiple data sources
        image: /images/pykale_logo_long.png
        featured:
          name: Website
          link: https://pykale.github.io/
        badges:
          - "Python"
          - "PyTorch"
          - "Deep Learning"
          - "Machine Learning"
          - "Multimodal Learning"
          - "Meta Learning"
          - "Knowledge Graph"
          - "Domain Adaptation"
        links:
          - icon: fab fa-github
            url: https://github.com/pykale/pykale

      - title: An Introduction to Transparent Machine Learning
        content:  An Introduction to Transparent Machine Learning, part of the Alan Turing Institute’s online learning courses in responsible AI.
        image: /images/transparentml-logo.png
        featured:
          name: Website
          link: https://pykale.github.io/transparentML/
        badges:
          - "Jupyter Book"
          - "Python"
          - "Sci-kit Learn"
          - "PyTorch"
        links:
          - icon: fab fa-github
            url: https://github.com/pykale/transparentML

      - title: EduBot
        content: An Android app that controls a small educational robot named EduBot.
        image: /images/pos_logo.jpg
        badges:
          - "Java"
          - "Android"
          - "Firebase"
          - "C++"
        links:
          - icon: fab fa-github
            url: https://github.com/Mdnaimulislam/EduBot-FinalApp

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: m.suvon@sheffield.ac.uk
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  #footer:
    #recentPosts:
      #path: "blogs"
      #count: 3
      #title: Recent Posts
      #enable: true
      #disableFeaturedImage: false
    #socialNetworks:
      #github: https://github.com
      #linkedin: https://linkedin.com
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "by Mohammod Suvon"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
